In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [6]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [7]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=np.float64)

In [8]:
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [9]:
b.dtype

dtype('float64')

In [10]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [11]:
np.zeros((3,3),'d')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.empty((4,4),'d')

array([[  6.91693215e-310,   8.33766212e-317,   0.00000000e+000,
          0.00000000e+000],
       [  6.91693296e-310,   6.91693301e-310,   6.91693296e-310,
          0.00000000e+000],
       [  0.00000000e+000,   6.91693305e-310,   0.00000000e+000,
          0.00000000e+000],
       [  6.91693296e-310,   6.91693296e-310,   6.91693296e-310,
          6.91693296e-310]])

In [13]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.random.standard_normal((2,4))

array([[ 0.70812076, -0.61291326, -0.7064038 ,  0.96824214],
       [-0.83231679,  1.48732078,  1.34350479,  0.64261487]])

In [18]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-0.15537422, -0.69367263, -1.0473199 ],
       [ 0.31381687, -0.82564959,  1.72547953],
       [ 0.13450148,  0.507265  , -1.26442319],
       [-1.02533288, -0.95763409, -0.94678402]])

In [19]:
np.hstack([a,b])

array([[-0.15537422, -0.69367263, -1.0473199 ,  0.13450148,  0.507265  ,
        -1.26442319],
       [ 0.31381687, -0.82564959,  1.72547953, -1.02533288, -0.95763409,
        -0.94678402]])

In [20]:
a.transpose()

array([[-0.15537422,  0.31381687],
       [-0.69367263, -0.82564959],
       [-1.0473199 ,  1.72547953]])

In [22]:
np.save('example.npy',a)

In [23]:
a1 = np.load('example.npy')

In [24]:
a1

array([[-0.15537422, -0.69367263, -1.0473199 ],
       [ 0.31381687, -0.82564959,  1.72547953]])