In [1]:
import numpy as np

In [3]:
v = np.linspace(0,10,5)

In [4]:
v[0]

0.0

In [5]:
v[1]

2.5

In [6]:
v[-1]

10.0

In [7]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [12]:
vv = np.random.random((5,4))

In [13]:
vv

array([[ 0.16329123,  0.17379703,  0.13674872,  0.73122495],
       [ 0.07639213,  0.30543954,  0.47491636,  0.65604302],
       [ 0.79486242,  0.99730512,  0.47064941,  0.19021148],
       [ 0.82005121,  0.54276861,  0.18162115,  0.56849481],
       [ 0.43459575,  0.08965311,  0.29372582,  0.79600458]])

In [14]:
vv[0,0]

0.16329122536018459

In [15]:
vv[4,3]

0.79600457835034844

In [16]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [18]:
ll[1][2]

6

# Slicing Numpy Array

In [19]:
v[2:4]

array([ 5. ,  7.5])

In [21]:
vv[2:5,1]

array([ 0.99730512,  0.54276861,  0.08965311])

In [22]:
vv[2:5,1:2]

array([[ 0.99730512],
       [ 0.54276861],
       [ 0.08965311]])

In [23]:
vv[2:-1,:]

array([[ 0.79486242,  0.99730512,  0.47064941,  0.19021148],
       [ 0.82005121,  0.54276861,  0.18162115,  0.56849481]])

In [24]:
vv[:,::2]

array([[ 0.16329123,  0.13674872],
       [ 0.07639213,  0.47491636],
       [ 0.79486242,  0.47064941],
       [ 0.82005121,  0.18162115],
       [ 0.43459575,  0.29372582]])

In [32]:
#changing affect in original array
v2 = v[2:4]

In [26]:
v2[0] = 0

In [27]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [28]:
v3 = v[2:4].copy()

In [30]:
v3[0] = 1

In [31]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [34]:
v[[1,2,3]]

array([ 2.5,  0. ,  7.5])

In [36]:
bool_index = v > 0

In [38]:
v[bool_index]

array([  2.5,   7.5,  10. ])

In [42]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [43]:
vv

array([[ 0.16329123,  0.17379703,  0.13674872,  5.84979959],
       [ 0.07639213,  0.30543954,  0.47491636,  5.24834419],
       [ 6.35889933,  7.97844093,  0.47064941,  0.19021148],
       [ 6.56040969,  4.34214885,  0.18162115,  4.5479585 ],
       [ 0.43459575,  0.08965311,  0.29372582,  6.36803663]])